import {Args, Command} from '@oclif/core'

import {renderPlatformPreview} from '../../lib/review-queue/platform-previews.js'
import {ReviewQueue} from '../../lib/review-queue/index.js'
import type {ReviewItem} from '../../lib/review-queue/index.js'

export default class ReviewShow extends Command {
  static override args = {
    id: Args.string({description: 'Review item ID to display', required: true}),
  }

  static override description = 'Show platform-specific content preview for a review item'

  static enableJsonFlag = true

  async run(): Promise<ReviewItem> {
    const {args} = await this.parse(ReviewShow)
    const projectRoot = process.cwd()
    const queue = new ReviewQueue(projectRoot)
    const item = await queue.getById(args.id)

    // Render platform-specific preview
    const preview = renderPlatformPreview(item)
    this.log(preview)

    // Display metadata
    this.log('')
    this.log('=== Item Details ===')
    this.log(`  ID:               ${item.id}`)
    this.log(`  Platform:         ${item.platform}`)
    this.log(`  Status:           ${item.status}`)
    this.log(`  Quality Score:    ${item.qualityScore}`)
    this.log(`  Content Type:     ${item.contentType}`)
    this.log(`  Generated By:     ${item.generatedBy}`)
    this.log(`  Generated At:     ${item.generatedAt}`)
    this.log(`  Compliance Flags: ${item.complianceFlags.length > 0 ? item.complianceFlags.join(', ') : 'None'}`)

    if (item.scheduledTime) {
      this.log(`  Scheduled Time:   ${item.scheduledTime}`)
    }

    return item
  }
}
